### DISCUSSION TITLE
Diagnose: What should I check if the obfuscation capabilities are not working?

### DISCUSSION THREAD

**Discussion by tal-lunar** [TheLunarCompany/lunar#8] [Q&A] [answered]
What should I check if the obfuscation capabilities are not working?

**Comment by tal-lunar** [comment, marked as answer]
Review the configuration in the [policies.yaml](http://localhost:3000/product-features/customize/) file. Make sure the `obfuscate` parameter is correctly placed under the `har_exporter` configuration.

Here's an example:

```
diagnosis:
  - name: "Export Obfuscated HAR Logs to S3"
    enabled: true
    config:
      har_exporter:
        transaction_max_size: 5000
        obfuscate:
          enabled: true
    export: s3
 ```
